os:
  - linux
language: generic
services:
  - docker
sudo: required
dist: trusty
before_install:
  - docker pull couchdb
  - docker image ls
  - chmod ugo+x ./install-swift.sh
  - . ./install-swift.sh
before_script:
  - docker run -d --name couchdb -p 5984:5984 -e COUCHDB_USER="admin" -e COUCHDB_PASSWORD="password" couchdb
script:
  - swift build
  - swift test
after_script:
  - docker stop couchdb