os:
  - linux
language: generic
services:
  - docker
sudo: required
dist: trusty
osx_image: xcode8.3
before_install:
  - docker pull ibmcom/swift-ubuntu
  - docker pull couchdb
  - docker image ls
script:
  - docker-compose -f docker-test.yml up